
<name>          ::=     <VariableNodeParser>

<root>          ::=     <expr>
<customValue>   ::=     "{" <name> "}"
<op>            ::=     "==" | ">" | "<" | ">=" | "<=" | "&&" | "||"
<expr>          ::=     "(" <expr> ")" | <customValue> | <expr> <op> <expr>